export const DEMO_ITEMS = [
  {
    id: 'demo-top-1',
    name: 'Camisa blanca',
    category: 'superior',
    color: 'Blanco',
    season: 'todas',
    imageUrl: '/demo/superior-1.jpg',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-top-2',
    name: 'Suéter beige',
    category: 'superior',
    color: 'Beige',
    season: 'invierno',
    imageUrl: '/demo/superior-2.jpg',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-bottom-1',
    name: 'Jeans azul',
    category: 'inferior',
    color: 'Azul',
    season: 'todas',
    imageUrl: '/demo/inferior-1.jpg',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-bottom-2',
    name: 'Pantalón negro',
    category: 'inferior',
    color: 'Negro',
    season: 'todas',
    imageUrl: '/demo/inferior-2.jpg',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-shoe-1',
    name: 'Zapatillas blancas',
    category: 'calzado',
    color: 'Blanco',
    season: 'todas',
    imageUrl: '/demo/calzado-1.jpg',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-shoe-2',
    name: 'Botas café',
    category: 'calzado',
    color: 'Café',
    season: 'invierno',
    imageUrl: '/demo/calzado-2.jpg',
    createdAt: new Date().toISOString(),
  },
]
