const stamp = 'v3'

export const DEMO_STORE_NAME = 'Atelier Norte'

/** Closet personal de ejemplo (lo que ya tienes en casa). */
export const DEMO_ITEMS = [
  {
    id: 'demo-top-1',
    name: 'Camisa blanca',
    category: 'superior',
    color: 'Blanco',
    season: 'todas',
    source: 'closet',
    imageUrl: `/demo/superior-1.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-top-2',
    name: 'Suéter beige',
    category: 'superior',
    color: 'Beige',
    season: 'invierno',
    source: 'closet',
    imageUrl: `/demo/superior-2.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-bottom-1',
    name: 'Jeans azul',
    category: 'inferior',
    color: 'Azul',
    season: 'todas',
    source: 'closet',
    imageUrl: `/demo/inferior-1.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-bottom-2',
    name: 'Pantalón negro',
    category: 'inferior',
    color: 'Negro',
    season: 'todas',
    source: 'closet',
    imageUrl: `/demo/inferior-2.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-shoe-1',
    name: 'Zapatillas blancas',
    category: 'calzado',
    color: 'Blanco',
    season: 'todas',
    source: 'closet',
    imageUrl: `/demo/calzado-1.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-shoe-2',
    name: 'Botas café',
    category: 'calzado',
    color: 'Café',
    season: 'invierno',
    source: 'closet',
    imageUrl: `/demo/calzado-2.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
]

/** Catálogo de tienda con imágenes propias (distintas al closet). */
export const STORE_ITEMS = [
  {
    id: 'store-top-1',
    name: 'Blazer lino arena',
    category: 'superior',
    color: 'Beige',
    season: 'verano',
    source: 'store',
    store: DEMO_STORE_NAME,
    brand: 'Norte Studio',
    price: 189000,
    imageUrl: `/demo/store-superior-1.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-top-2',
    name: 'Camisa oxford crisp',
    category: 'superior',
    color: 'Blanco',
    season: 'todas',
    source: 'store',
    store: DEMO_STORE_NAME,
    brand: 'Norte Studio',
    price: 129000,
    imageUrl: `/demo/store-superior-2.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-bottom-1',
    name: 'Wide jeans indigo',
    category: 'inferior',
    color: 'Azul',
    season: 'todas',
    source: 'store',
    store: DEMO_STORE_NAME,
    brand: 'Calle 7',
    price: 159000,
    imageUrl: `/demo/store-inferior-1.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-bottom-2',
    name: 'Trouser negro slim',
    category: 'inferior',
    color: 'Negro',
    season: 'todas',
    source: 'store',
    store: DEMO_STORE_NAME,
    brand: 'Calle 7',
    price: 149000,
    imageUrl: `/demo/store-inferior-2.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-shoe-1',
    name: 'Sneaker city white',
    category: 'calzado',
    color: 'Blanco',
    season: 'todas',
    source: 'store',
    store: DEMO_STORE_NAME,
    brand: 'Paso Urbano',
    price: 219000,
    imageUrl: `/demo/store-calzado-1.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-shoe-2',
    name: 'Boot chelsea café',
    category: 'calzado',
    color: 'Café',
    season: 'invierno',
    source: 'store',
    store: DEMO_STORE_NAME,
    brand: 'Paso Urbano',
    price: 279000,
    imageUrl: `/demo/store-calzado-2.jpg?${stamp}`,
    createdAt: new Date().toISOString(),
  },
]

export function formatCop(amount) {
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    maximumFractionDigits: 0,
  }).format(amount)
}
